import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (relativePath) => readFileSync(join(root, relativePath), 'utf8')

test('Phase 0 stores provider profiles while retaining the legacy API-key fields', () => {
  const types = read('src/main/lib/types.ts')
  const store = read('src/main/lib/store.ts')
  assert.match(types, /LlmProviderId = 'openai-compatible' \| 'codex-app-server'/)
  assert.match(types, /interface LlmConnectionProfile/)
  assert.match(types, /activeLlmConnectionId: string/)
  assert.match(types, /llmConnections: LlmConnectionProfile\[\]/)
  assert.match(store, /LEGACY_LLM_CONNECTION_ID = 'openai-compatible-default'/)
  assert.match(store, /CHATGPT_LLM_CONNECTION_ID = 'chatgpt-codex'/)
  assert.match(store, /normalizeLlmConnections/)
  assert.match(store, /DEFAULT_OPENAI_MODEL = 'gpt-5-mini'/)
  assert.match(types, /setupStatus\?: LlmSetupStatus/)
  assert.match(store, /llmConnectionSchemaVersion: 3/)
  assert.match(store, /connectionsWithVerification/)
  assert.match(store, /llmModel: active\?\.model \?\? persisted\.llmModel/)
  assert.match(store, /llmApiKeys\?: Record<string, SecretValue>/)
  assert.match(store, /saveLlmApiKeyForConnection/)
  assert.match(store, /getLlmApiKey/)
})

test('Codex App Server uses isolated login, real dynamic tools, streaming, and image input', () => {
  const client = read('src/main/services/llm/codexAppServerClient.ts')
  const runtime = read('src/main/services/llm/codexAppServerAgentRuntime.ts')
  assert.match(client, /'app-server', '--listen', 'stdio:\/\/'/)
  assert.match(client, /@openai\/codex-win32-x64/)
  assert.match(client, /process\.resourcesPath/)
  assert.match(client, /resolveCodexExecutable/)
  assert.doesNotMatch(client, /return 'codex'/)
  assert.match(client, /CODEX_HOME = join\(appHome, 'codex'\)/)
  assert.match(client, /cli_auth_credentials_store="file"/)
  assert.match(client, /request\('initialize'/)
  assert.match(client, /experimentalApi: true/)
  assert.match(client, /notify\('initialized'/)
  assert.match(client, /account\/read/)
  assert.match(client, /account\/login\/start/)
  assert.match(client, /useHostedLoginSuccessPage: true/)
  assert.match(client, /account\/logout/)
  assert.match(client, /model\/list/)
  assert.match(client, /includeHidden: true/)
  assert.match(client, /inputModalities/)
  assert.match(client, /stdin\.destroyed/)
  assert.match(client, /child\.stdin\.on\('error'/)
  assert.match(client, /class CodexTransportError/)
  assert.match(client, /private async requestWithRestart/)
  assert.match(client, /RPC_TIMEOUT_MS = 20_000/)
  assert.match(client, /Codex App Server 请求超时/)
  assert.match(client, /this\.events\.emit\('transport-failure'/)
  assert.match(client, /waitForTurnCompletion/)
  assert.match(client, /if \(this\.child !== child\) return/)
  assert.match(client, /handleProcessFailure/)
  assert.match(client, /type: 'localImage'/)
  assert.match(client, /function readOnlySandbox/)
  assert.match(client, /type: 'readOnly'/)
  assert.match(client, /networkAccess: false/)
  assert.match(client, /runtimeWorkspaceRoots: \[tempRoot\]/)
  assert.match(client, /sandboxPolicy: readOnlySandbox\(\)/)
  assert.match(client, /dynamicTools: dynamicTools\(tools\)/)
  assert.match(client, /item\/tool\/call/)
  assert.match(client, /contentItemsFromToolResult/)
  assert.match(client, /if \(result\.ok\) context\.executedTools\.push\(toolName\)/)
  assert.match(client, /success: result\.ok/)
  assert.match(client, /FORBIDDEN_ITEM_TYPES/)
  assert.match(client, /policyViolations/)
  assert.match(client, /item\/agentMessage\/delta/)
  assert.match(client, /turn\/completed/)
  assert.match(client, /turn\/interrupt/)
  assert.match(client, /request\('thread\/delete'/)
  assert.doesNotMatch(client, /apiKey:\s*profile/)
  assert.match(runtime, /class CodexAppServerAgentRuntime implements AgentRuntimeAdapter/)
  assert.match(runtime, /goagent_healthEcho/)
  assert.match(runtime, /图片识别正常/)
})

test('ChatGPT credentials are checked before OAuth and model defaults come from provider discovery', () => {
  const registry = read('src/main/services/llm/providerRegistry.ts')
  const onboarding = read('src/renderer/src/features/onboarding/FirstRunOnboarding.tsx')
  const i18n = read('src/renderer/src/i18n.ts')
  const packageJson = JSON.parse(read('package.json'))
  assert.match(registry, /connectionState\(profile\.id\)/)
  assert.match(registry, /if \(state\.ready\)/)
  assert.match(registry, /function selectCodexModel/)
  assert.match(registry, /model\.supportsImage === true/)
  assert.match(read('src/main/services/llm/codexAppServerClient.ts'), /supportsImage: modalities \? modalities\.includes\('image'\) : undefined/)
  assert.match(registry, /recommendedModel: selected\?\.id/)
  assert.match(onboarding, /result\.recommendedModel \|\| result\.models\[0\]/)
  assert.match(onboarding, /chatGptLoginPending/)
  assert.doesNotMatch(onboarding, /setInterval/)
  assert.match(onboarding, /t\('chatGptLoggedIn'\)/)
  assert.match(i18n, /chatGptLoggedIn: 'GoAgent 已登录 ChatGPT，可以继续。'/)
  assert.match(i18n, /chatGptLoggedIn: 'GoAgent is signed in to ChatGPT and ready to continue.'/)
  assert.equal(packageJson.devDependencies['@openai/codex'], '0.149.0')
  assert.equal(packageJson.dependencies['@openai/codex'], undefined)
  assert.equal(packageJson.build.afterPack, 'build/afterPack.cjs')
  assert.deepEqual(packageJson.build.asarUnpack, [])
})

test('Both providers use the tool-first evidence loop while Codex receives only domain tools', () => {
  const registry = read('src/main/services/llm/providerRegistry.ts')
  const teacher = read('src/main/services/teacherAgent.ts')
  const adapters = read('src/main/services/llm/agentRuntime.ts')
  assert.match(registry, /runProviderTurn/)
  assert.match(registry, /runtimeFor\(profile\)\.runTurn/)
  assert.match(registry, /CODEX_DOMAIN_TOOL_NAMES/)
  assert.match(registry, /toolsForLlmConnection/)
  assert.doesNotMatch(registry.match(/const CODEX_DOMAIN_TOOL_NAMES[\s\S]*?\]\)/)?.[0] ?? '', /shell_exec|filesystem_read|web_searchGoKnowledge|settings_writeAppConfig/)
  assert.match(adapters, /interface AgentRuntimeAdapter/)
  assert.match(adapters, /executeTool\?: AgentToolExecutor/)
  assert.match(adapters, /ok: boolean/)
  assert.doesNotMatch(teacher, /prefetchEvidenceForManagedProvider/)
  assert.match(teacher, /katago_analyzePosition/)
  assert.match(teacher, /katago_analyzeGameBatch/)
  assert.match(teacher, /board_captureTeachingImage/)
  assert.match(teacher, /knowledge_matchPosition/)
  assert.match(teacher, /successfulAgentTools/)
  assert.match(teacher, /if \(result\.ok\) successfulAgentTools\.add/)
  assert.match(teacher, /runProviderTurn\(settings, messages/)
})

test('ChatGPT login is exposed without tokens and unrelated Python review remains intact', () => {
  const main = read('src/main/index.ts')
  const preload = read('src/preload/index.ts')
  const globalTypes = read('src/renderer/src/global.d.ts')
  const app = read('src/renderer/src/App.tsx')
  assert.match(main, /llm:chatgpt-login/)
  assert.match(main, /shell\.openExternal\(url\)/)
  assert.doesNotMatch(main, /await shell\.openExternal\(url\)/)
  assert.match(main, /dashboard\(llmConnection\)/)
  assert.match(preload, /startChatGptLogin/)
  assert.match(preload, /logoutChatGpt/)
  assert.match(globalTypes, /startChatGptLogin/)
  assert.match(app, /ChatGPT 登录/)
  assert.match(app, /systemProfile\.llmConnection\.ready/)
  const loginBridge = preload.match(/startChatGptLogin:[\s\S]*?logoutChatGpt:[^\n]+/)?.[0] ?? ''
  assert.doesNotMatch(loginBridge, /accessToken|refreshToken/)
  assert.equal(existsSync(join(root, 'scripts/review_game.py')), true)
  assert.equal(existsSync(join(root, 'src/main/services/review.ts')), true)
  assert.match(main, /review:start/)
})

test('Codex native runtimes are pinned, checksummed, and copied per package architecture', () => {
  const packageJson = JSON.parse(read('package.json'))
  const manifest = JSON.parse(read('data/codex/manifest.json'))
  const prepare = read('scripts/prepare_codex_runtime.mjs')
  const check = read('scripts/check_codex_runtime.mjs')
  const packagedSmoke = read('scripts/smoke_codex_packaged_runtime.mjs')
  const afterPack = read('build/afterPack.cjs')
  assert.equal(existsSync(join(root, 'data/codex/LICENSE')), true)
  assert.equal(manifest.version, '0.149.0')
  for (const target of ['darwin-arm64', 'darwin-x64', 'win32-x64', 'linux-x64', 'linux-arm64']) {
    assert.match(manifest.targets[target].sha256, /^[a-f0-9]{64}$/)
    assert.ok(manifest.targets[target].bytes > 100_000_000)
  }
  assert.match(prepare, /Codex runtime checksum mismatch/)
  assert.match(check, /failed to report Codex/)
  assert.match(afterPack, /context\.electronPlatformName/)
  assert.match(afterPack, /Codex runtime validation failed/)
  assert.match(afterPack, /data', 'codex', 'LICENSE'/)
  assert.match(packagedSmoke, /packaged Codex license is missing/)
  assert.match(packagedSmoke, /expected packaged target was not found/)
  assert.match(packagedSmoke, /failed to start as Codex/)
  assert.match(packagedSmoke, /initializePackagedAppServer/)
  assert.match(packagedSmoke, /'app-server', '--listen', 'stdio:\/\/'/)
  assert.match(packagedSmoke, /method: 'thread\/start'/)
  assert.match(packagedSmoke, /runtimeWorkspaceRoots: \[codexHome\]/)
  assert.match(packagedSmoke, /App Server thread initialized from/)
  assert.match(packagedSmoke, /validSignedMacRuntime/)
  assert.match(packagedSmoke, /accepted signed package transforms/)
  assert.match(read('.github/workflows/release.yml'), /Verify packaged Codex App Server/)
  assert.match(read('.gitignore'), /data\/codex\/bin/)
  assert.equal(packageJson.scripts['check:codex-runtime'], 'node scripts/check_codex_runtime.mjs --mode=dev')
  assert.equal(packageJson.scripts['smoke:codex-runtime'], 'node scripts/smoke_codex_packaged_runtime.mjs')
  assert.match(packageJson.scripts['package:dir'], /electron-builder --dir/)
  assert.match(packageJson.scripts['package:dir'], /signAndEditExecutable=false/)
  assert.match(read('.github/workflows/ci.yml'), /- name: Test/)
  assert.match(read('.github/workflows/ci.yml'), /Package directory with embedded Codex runtime/)
  assert.match(read('.github/workflows/ci.yml'), /Initialize packaged Codex App Server/)
})
