import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'
import ts from 'typescript'

const root = process.cwd()

function read(relativePath) {
  return readFileSync(join(root, relativePath), 'utf8')
}

async function importRendererModule(relativePath) {
  const source = read(relativePath)
  const compiled = ts.transpileModule(source, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ES2022,
      jsx: ts.JsxEmit.ReactJSX,
      importsNotUsedAsValues: ts.ImportsNotUsedAsValues.Remove
    }
  }).outputText
  return import(`data:text/javascript;base64,${Buffer.from(compiled, 'utf8').toString('base64')}`)
}

test('Sprint 7 UI Gallery route and mock data are present', () => {
  assert.equal(existsSync(join(root, 'src/renderer/src/features/gallery/UiGallery.tsx')), true)
  assert.equal(existsSync(join(root, 'src/renderer/src/features/gallery/uiGalleryMock.ts')), true)
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /#\/ui-gallery/)
  assert.match(app, /UiGallery/)
})

test('GoBoardV2 renders polished stone and candidate layers', () => {
  const board = read('src/renderer/src/features/board/GoBoardV2.tsx')
  const boardCss = read('src/renderer/src/features/board/board-v2.css')
  const styles = read('src/renderer/src/styles.css')
  assert.match(board, /ks-stone-highlight/)
  assert.match(board, /ks-board-bevel/)
  assert.match(board, /ks-candidate-soft-glow/)
  assert.match(board, /ks-candidate-winrate/)
  assert.match(board, /ks-candidate-visits/)
  assert.match(board, /ks-candidate-score/)
  assert.match(board, /PlayedMoveMark/)
  assert.match(board, /ks-played-move-layer/)
  assert.match(board, /VariationPreview/)
  assert.match(board, /ks-variation-preview-layer/)
  assert.match(board, /candidateVariationMoves/)
  assert.match(board, /ks-candidate-hitarea/)
  assert.match(board, /handleBoardPointerMove/)
  assert.match(board, /hitRadius/)
  assert.match(board, /cursorInActivePreview/)
  assert.match(board, /variationPreviewMoves/)
  assert.match(board, /active=\{sameCandidate/)
  assert.match(board, /onMouseMove=\{handleBoardPointerMove\}/)
  assert.doesNotMatch(board, /<CandidateTooltip/)
  assert.match(boardCss, /\.ks-candidates-layer\s*\{[^}]*pointer-events:\s*none/s)
  assert.match(boardCss, /\.ks-candidate--active \.ks-candidate-ring/)
  assert.doesNotMatch(boardCss, /\.ks-candidate:hover\s*\{[^}]*transform/s)
  assert.match(boardCss, /\.ks-played-move--W \.ks-played-move-frame\s*\{[^}]*255,\s*250,\s*235/s)
  assert.match(boardCss, /\.ks-played-move--B \.ks-played-move-frame\s*\{[^}]*12,\s*13,\s*13/s)
  assert.match(boardCss, /\.ks-candidate-winrate\s*\{[^}]*font-size:\s*12\.8px/s)
  assert.match(boardCss, /\.ks-played-move-winrate\s*\{[^}]*font-size:\s*12\.6px/s)
  assert.match(board, /function PreviousMoveMarker/)
  assert.match(board, /previousMoveNumber = moveNumber > 1 \? moveNumber - 1 : -1/)
  assert.match(board, /ks-previous-move-gem/)
  assert.match(board, /ks-stone--previous/)
  assert.doesNotMatch(board, /lastStone/)
  assert.match(boardCss, /\.ks-previous-move-gem\s*\{[^}]*stroke-width:\s*1\.35/s)
  assert.match(boardCss, /\.ks-previous-move-glint\s*\{[^}]*stroke-linecap:\s*round/s)
  assert.match(boardCss, /calc\(100dvh - 232px\)/)
  assert.match(styles, /calc\(100dvh - 212px\),\s*980px/)
  assert.doesNotMatch(boardCss, /820px/)
  assert.match(styles, /grid-template-rows:\s*44px minmax\(0,\s*1fr\) 118px/)
  const geometry = read('src/renderer/src/features/board/boardGeometry.ts')
  assert.match(geometry, /renderPlayedMove/)
  assert.match(geometry, /RenderVariationMove/)
  assert.match(geometry, /candidateVariationMoves/)
  assert.match(geometry, /valueOf\(valueOf\(analysis, 'before'\), 'topMoves'\)/)
  assert.match(geometry, /type RenderBoard = Map<string, RenderStone>/)
  assert.match(geometry, /function collectRenderGroup/)
  assert.match(geometry, /function groupLiberties/)
  assert.match(geometry, /function removeRenderGroup/)
  assert.match(geometry, /function playRenderMove/)
  assert.match(geometry, /record\.initialStones/)
  assert.match(geometry, /groupLiberties\(board, group, boardSize\) === 0/)
  assert.doesNotMatch(geometry, /moves\.slice\(0, Math\.max\(0, moveNumber\)\)\.flatMap/)
})

test('GoBoardV2 stone rendering reconstructs captures before drawing stones', async () => {
  const { renderStones } = await importRendererModule('src/renderer/src/features/board/boardGeometry.ts')
  const moves = [
    ['B', 0, 1],
    ['W', 1, 1],
    ['B', 0, 2],
    ['W', 1, 2],
    ['B', 1, 0],
    ['W', 4, 4],
    ['B', 1, 3],
    ['W', 4, 3],
    ['B', 2, 1],
    ['W', 3, 3],
    ['B', 2, 2],
    ['W', 1, 1]
  ].map(([color, row, col], index) => ({
    moveNumber: index + 1,
    color,
    point: `${row}${col}`,
    row,
    col,
    gtp: `${row}-${col}`,
    pass: false
  }))
  const record = { boardSize: 5, moves, komi: '0', handicap: '0', game: { id: 'capture-fixture' } }
  const afterCapture = renderStones(record, 11)
  assert.equal(afterCapture.some((stone) => stone.x === 1 && stone.y === 1), false)
  assert.equal(afterCapture.some((stone) => stone.x === 2 && stone.y === 1), false)

  const afterReoccupy = renderStones(record, 12)
  const reoccupied = afterReoccupy.find((stone) => stone.x === 1 && stone.y === 1)
  assert.equal(reoccupied?.color, 'W')
  assert.equal(reoccupied?.moveNumber, 12)
  assert.equal(afterReoccupy.some((stone) => stone.x === 2 && stone.y === 1), false)
})

test('Current-move teacher screenshot has procedural asset fallback', () => {
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /function loadBoardPngAssets/)
  assert.match(app, /Promise\.allSettled/)
  assert.match(app, /paintProceduralBoardTexture/)
  assert.match(app, /paintProceduralStone/)
  assert.match(app, /return renderBoardPng\(record, moveNumber, analysis, false\)/)
  assert.doesNotMatch(app, /await Promise\.all\(\[\s*loadCanvasImage\(lizzieBoardUrl\)/s)

  const smoke = read('scripts/teacher_llm_smoke.mjs')
  assert.match(smoke, /teacher composer/)
  assert.match(smoke, /ks-composer-pro__send/)
  assert.match(smoke, /无法加载棋盘素材/)
  assert.match(smoke, /UI current-move analysis should render the teacher answer/)
})

test('WinrateTimelineV2 exposes hover tooltip and severity markers on a single-line KPI header', () => {
  const timeline = read('src/renderer/src/features/board/WinrateTimelineV2.tsx')
  assert.match(timeline, /ks-timeline-tooltip/)
  assert.match(timeline, /ks-timeline-severity-legend/)
  assert.match(timeline, /ks-timeline-kpi--winrate/)
  assert.match(timeline, /ks-timeline-kpi--score/)
  assert.match(timeline, /t\('timelineScoreLead'\)/)
  assert.match(timeline, /t\('timelineCurrentBlackWinrate'\)/)
  assert.match(timeline, /t\('timelinePreviousMove'\)/)
  assert.match(timeline, /t\('timelineNextMove'\)/)
  assert.match(timeline, /t\('timelineSeverityHeader'\)/)
  assert.match(timeline, /ArrowLeft/)
  assert.match(timeline, /ArrowRight/)
  assert.match(timeline, /ks-timeline-move-count/)
  assert.match(timeline, /playedMove'\), 'winrateLoss'/)
  // severity markers must be rendered on the curve
  assert.match(timeline, /ks-timeline-dot--\$\{point\.severity\}/)
  assert.match(timeline, /extractScoreLead/)
  assert.match(timeline, /hoveredMove/)
  assert.match(timeline, /formatBlackWinrate/)
  assert.match(timeline, /ks-timeline-nav/)
  assert.match(timeline, /getScreenCTM\(\)\?\.inverse\(\)/)
  assert.match(timeline, /moveFromTimelineSvgX/)
  assert.match(timeline, /x1=\{x\(hoveredMove\)\}/)
  const boardCss = read('src/renderer/src/features/board/board-v2.css')
  // single-line flex header
  assert.match(boardCss, /\.ks-timeline-head\s*\{[^}]*display:\s*flex/s)
  // severity markers on the curve in three intensity tones
  assert.match(boardCss, /\.ks-timeline-dot--blunder\s*\{[^}]*--ks-red/s)
  assert.match(boardCss, /\.ks-timeline-dot--mistake\s*\{[^}]*--ks-orange/s)
  assert.match(boardCss, /\.ks-timeline-dot--inaccuracy\s*\{[^}]*--ks-gold/s)
  // light surface canvas, not the old dark gradient
  assert.match(boardCss, /\.ks-timeline-canvas\s*\{[^}]*--ks-bg-elevated/s)
  assert.doesNotMatch(boardCss, /\.ks-timeline-canvas\s*\{[^}]*#171d24/s)
})

test('KataGo live analysis controls expose start pause and visit thresholds', () => {
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /BoardContextBar/)
  assert.match(app, /LIVE_ANALYSIS_VISIT_STEPS/)
  assert.match(app, /LIVE_ANALYSIS_TOTAL_VISIT_LIMIT/)
  assert.match(app, /LIVE_ANALYSIS_BEST_VISIT_LIMIT/)
  assert.match(app, /visitsPerSecond/)
  assert.match(app, /analyzePositionStream/)
  assert.match(app, /group:\s*'live'/)
  assert.match(app, /cancelKataGoWork/)
  assert.match(app, /cancelKataGoWork\(\{\s*group:\s*'quick'\s*\}\)/)
  assert.match(app, /连接分析引擎 · 第/)
  assert.match(app, /kataGoRuntimeErrorMessage/)
  assert.match(app, /智子云远程 worker 返回额度不足或不可分配/)
  assert.match(app, /cancelKataGoAnalysis/)
  assert.match(app, /onAnalyzePositionProgress/)
  assert.match(app, /onAnalyzePositionSearchProgress/)
  assert.match(app, /实时搜索/)
  assert.doesNotMatch(app, /Math\.max\(lastSpeedSample, measuredSpeed\)/)
  const katago = read('src/main/services/katago.ts')
  assert.match(katago, /activeKataGoProcesses/)
  assert.match(katago, /cancelKataGoAnalysis/)
  assert.match(katago, /replaceGroup/)
  assert.match(katago, /reportDuringSearchEvery/)
  assert.match(katago, /isDuringSearch/)
  assert.match(katago, /latestBefore\?\.rootInfo && latestAfter\?\.rootInfo/)
  assert.match(katago, /return partial/)
  const mainIndex = read('src/main/index.ts')
  assert.match(mainIndex, /const group = payload\.group \?\?/)
  assert.match(mainIndex, /katago:analyze-position-search-progress/)
  assert.match(mainIndex, /priority: group === 'live' \|\| group === 'single'/)
  assert.match(mainIndex, /replaceGroup: group === 'live' \|\| !payload\.runId/)
  assert.match(mainIndex, /已取消\|cancel\|replaced\|替换\|停止/)
  assert.match(app, /formatSearchSpeed/)
  assert.match(app, /userPausedLiveAnalysisRef/)
  assert.match(app, /autoAnalysisRequestId/)
  assert.match(app, /queueAutoLiveAnalysis/)
  assert.match(app, /queueAutoLiveAnalysis\(selectedGame\.id, record, targetMove\)/)
  assert.match(app, /queueAutoLiveAnalysis\(gameId, next, next\.moves\.length, 120\)/)
  assert.doesNotMatch(app, /切换手数，已暂停精读/)
  assert.match(app, /老师讲解中，暂停精读/)
  assert.match(app, /讲解完成，已暂停精读/)
  assert.match(app, /KataGo 分析超时/)
  assert.match(app, /已保留/)
  assert.match(app, /startLiveAnalysis/)
  assert.match(app, /pauseLiveAnalysis/)
  assert.match(app, /t\('startAnalysis'\)/)
  assert.match(app, /t\('pauseAnalysis'\)/)
  assert.match(app, /timelineIssuesFromEvaluations/)
  assert.match(app, /timelineIssueColor/)
  assert.match(app, /TIMELINE_ISSUE_MIN_LOSS/)
  const styles = read('src/renderer/src/styles.css')
  assert.match(styles, /board-contextbar__metrics/)
  assert.match(styles, /analysis-control-strip/)
  assert.match(styles, /analysis-toggle-button/)
  assert.match(styles, /timeline-issues/)
  const timeline = read('src/renderer/src/features/board/WinrateTimelineV2.tsx')
  assert.match(timeline, /currentBlackWinrateLabel/)
  assert.match(timeline, /ks-timeline-kpi--winrate/)
})

test('KataGo benchmark tuning is wired from main process to settings UI', () => {
  const types = read('src/main/lib/types.ts')
  assert.match(types, /KataGoBenchmarkResult/)
  assert.match(types, /katagoBenchmarkThreads/)
  const runtime = read('src/main/services/katagoRuntime.ts')
  assert.match(runtime, /numAnalysisThreads = \$\{analysisThreads\}/)
  assert.match(runtime, /numSearchThreadsPerAnalysisThread = \$\{searchThreadsPerAnalysisThread\}/)
  const benchmark = read('src/main/services/katagoBenchmark.ts')
  assert.match(benchmark, /benchmark/)
  assert.match(benchmark, /numSearchThreads/)
  assert.match(benchmark, /visitsPerSecond/)
  const preload = read('src/preload/index.ts')
  assert.match(preload, /benchmarkKataGo/)
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /KataGoBenchmarkPanel/)
  assert.match(app, /t\('benchmarkRun'\)/)
})

test('TeacherRunCardPro behaves like an AI editor response instead of a fixed report card', () => {
  const teacher = read('src/renderer/src/features/teacher/TeacherRunCardPro.tsx')
  assert.match(teacher, /ks-teacher-pro-markdown/)
  assert.match(teacher, /查看工具调用/)
  assert.match(teacher, /GoAgent 回复/)
  assert.match(teacher, /正在读取棋盘、KataGo数据，正在开始分析。/)
  assert.match(teacher, /准备局面快照 · 获取候选点 · 检索证据链 · 组织老师讲解/)
  assert.doesNotMatch(teacher, /推荐思路/)
  assert.doesNotMatch(teacher, /可继续追问/)
  assert.doesNotMatch(teacher, /一句话结论/)
  assert.doesNotMatch(teacher, /ks-teacher-pro-evidence/)
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /teacher-agent-editor/)
  assert.match(app, /TeacherInlineResponse/)
  assert.match(app, /codex-tool-trace/)
  assert.match(app, /teacherToolTitle/)
  assert.match(app, /toolKatagoCurrent/)
  assert.match(app, /toolKatagoRecheck/)
  assert.match(app, /teacherToolTraceSummary/)
  assert.match(app, /toolDetailKatagoSecond/)
  assert.match(app, /t\('workingShort'\)/)
  assert.match(app, /codex-working--active/)
  assert.match(app, /1段以下/)
  assert.match(app, /9段/)
  assert.match(app, /normalizeUiStudentRank/)
  assert.match(app, /role="search"/)
  assert.match(app, /type="search"/)
  assert.match(app, /aria-label=\{t\('searchHistory'\)\}/)
  assert.match(app, /aria-label=\{t\('clearSearch'\)\}/)
  assert.match(app, /aria-label=\{`\$\{t\('deleteSession'\)\} \$\{session\.title\}`\}/)
  assert.match(app, /onClick=\{\(\) => onQuickPrompt\(item\)\}/)
  assert.match(app, /onPersonaSettingsSaved\(updated\)/)
  assert.doesNotMatch(app, /teacher-history-tabs/)
  assert.doesNotMatch(app, /TeacherHistoryFilter/)
  assert.doesNotMatch(app, /setHistoryFilter/)
  assert.doesNotMatch(app, /log\.detail \|\| log\.status/)
  assert.match(app, /onTeacherRunProgress/)
  assert.match(app, /assistant-delta/)
  assert.match(app, /scrollIntoView/)
  assert.match(app, /streaming-cursor/)
  assert.match(app, /copyTextToClipboard/)
  assert.match(app, /navigator\.clipboard/)
  assert.match(app, /t\('copyTeacherReply'\)/)
  assert.match(app, /assistant-copybar/)
  assert.match(app, /agent-turn/)
  assert.match(app, /aria-label=\{t\('teacherThread'\)\}/)
  assert.doesNotMatch(app, /你可以直接问/)
  const styles = read('src/renderer/src/styles.css')
  assert.match(styles, /assistant-copybar/)
  assert.match(styles, /user-select: text/)
  assert.match(styles, /codex-tool-title-shimmer/)
  assert.match(styles, /codex-tool-dot-pulse/)
  assert.match(styles, /teacher-working-text-breathe/)
  assert.match(styles, /teacher-working-sheen/)
  assert.match(styles, /codex-tool-trace__copy/)
  assert.match(styles, /teacher-tool-row-breathe/)
  assert.match(styles, /\.teacher-editor-head\s*\{[^}]*z-index:\s*60/s)
  assert.match(styles, /\.teacher-editor-actions\s*\{[^}]*z-index:\s*70/s)
  assert.match(styles, /\.teacher-panel\.teacher-agent-editor > \.teacher-editor-head\s*\{[^}]*z-index:\s*90/s)
  assert.match(styles, /\.teacher-panel\.teacher-agent-editor > \.message-list\.agent-thread\s*\{[^}]*z-index:\s*1/s)
  assert.match(styles, /\.teacher-editor-actions button:hover,\s*\.teacher-editor-actions button:focus-visible\s*\{[^}]*z-index:\s*5/s)
  assert.match(styles, /z-index:\s*1000/)
  assert.match(styles, /\.teacher-history-drawer\s*\{[^}]*top:\s*58px/s)
  assert.match(styles, /\.teacher-history-search\s*\{[^}]*grid-template-columns:\s*18px minmax\(0,\s*1fr\) auto/s)
  assert.match(styles, /\.teacher-history-item__delete/)
  assert.match(styles, /\.teacher-popover-error/)
  assert.doesNotMatch(styles, /\.teacher-history-tabs/)
  const teacherStyles = read('src/renderer/src/features/teacher/teacher-pro.css')
  assert.match(teacherStyles, /ks-teacher-pro-summary small/)
  assert.match(teacherStyles, /teacher-tool-row-breathe/)
  assert.match(app, /t\('foxSearch'\)/)
  const composer = read('src/renderer/src/features/teacher/TeacherComposerPro.tsx')
  assert.match(composer, /Ask GoAgent/)
  assert.match(composer, /ks-composer-pro__actions/)
  assert.match(composer, /ks-composer-pro__chrome/)
  assert.match(composer, /onStop/)
  assert.match(composer, /aria-label=\{busy \? translate\('stopGenerating'\) : translate\('send'\)\}/)
  assert.match(composer, /\{busy \? translate\('stopGenerating'\) : translate\('send'\)\}/)
  assert.doesNotMatch(composer, /问任何复盘问题/)
  const preload = read('src/preload/index.ts')
  const main = read('src/main/index.ts')
  assert.match(preload, /cancelTeacherRun/)
  assert.match(main, /teacher:cancel-run/)
  const agent = read('src/main/services/teacherAgent.ts')
  assert.match(agent, /runTeacherAgentSession/)
  assert.match(agent, /runProviderTurn/)
  assert.match(agent, /cancelTeacherRun/)
  assert.match(agent, /AbortController/)
  assert.match(agent, /老师任务已停止/)
  assert.match(agent, /shell_exec/)
  assert.match(agent, /emitAssistantDelta/)
  assert.match(agent, /assistant-start/)
  const provider = read('src/main/services/llm/openaiCompatibleProvider.ts')
  assert.match(provider, /streamOpenAICompatibleChat/)
  assert.match(provider, /streamOpenAICompatibleToolTurn/)
  assert.match(provider, /extractToolCalls/)
  assert.match(provider, /onDelta/)
  assert.doesNotMatch(agent, /请优先输出 JSON/)
  assert.doesNotMatch(agent, /讲当前手时优先回答/)
  assert.doesNotMatch(agent, /这手想法哪里偏/)
  assert.doesNotMatch(agent, /KataGo 数字只作为证据/)
  assert.doesNotMatch(agent, /不要把答案写成机器报告/)
})

test('Desktop app shell exposes native menu commands and workbench chrome', () => {
  const main = read('src/main/index.ts')
  assert.match(main, /Menu\.setApplicationMenu/)
  assert.match(main, /desktop:command/)
  assert.match(main, /CommandOrControl\+K/)
  const preload = read('src/preload/index.ts')
  assert.match(preload, /onDesktopCommand/)
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /DesktopTitleBar/)
  assert.match(app, /CommandPalette/)
  assert.match(app, /DesktopPreferencesModal/)
  assert.match(app, /DesktopStatusBar/)
  assert.match(app, /t\('settings'\)/)
  assert.doesNotMatch(app, /AI Go Workbench<\/span>/)
  assert.doesNotMatch(app, />Command<\/button>/)
  assert.doesNotMatch(app, />Preferences<\/button>/)
  assert.doesNotMatch(app, /'LLM 配置'>⚙/)
  const styles = read('src/renderer/src/styles.css')
  assert.match(styles, /desktop-shell/)
  assert.match(styles, /desktop-command-palette/)
  assert.match(styles, /desktop-statusbar/)
  assert.match(styles, /desktop-command-palette__list strong[^}]+#f8f1e4/s)
  assert.match(styles, /desktop-command-palette__panel input::placeholder/)
})

test('StudentRailCard stays compact and visual QA capture exists', () => {
  const student = read('src/renderer/src/features/student/StudentRailCard.tsx')
  assert.match(student, /unboundPlayer/)
  assert.match(student, /onChangeBinding/)
  assert.doesNotMatch(student, /Fox \$\{primaryFoxNickname\}/)
  assert.doesNotMatch(student, /gameCount} 盘/)
  assert.doesNotMatch(student, /trainingFocus/)
  assert.doesNotMatch(student, /分析最近 10 局/)
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /loadBoundPlayer/)
  const main = read('src/main/index.ts')
  assert.match(main, /student:for-game/)
  const preload = read('src/preload/index.ts')
  assert.match(preload, /getStudentForGame/)
  assert.equal(existsSync(join(root, 'scripts/capture_ui_gallery.mjs')), true)
  assert.equal(existsSync(join(root, 'docs/VISUAL_QA_CAPTURE.md')), true)
  const capture = read('scripts/capture_ui_gallery.mjs')
  const visualDocs = read('docs/VISUAL_QA_CAPTURE.md')
  assert.match(capture, /\['teaching-artifact-card',\s*'\.teacher-artifact-card'\]/)
  assert.match(capture, /locator\.screenshot/)
  assert.match(visualDocs, /Teaching Artifact/i)
  assert.match(visualDocs, /teaching-artifact-card\.png/)
  assert.match(visualDocs, /coaching card/i)
  const galleryStyles = read('src/renderer/src/features/gallery/ui-gallery.css')
  assert.match(galleryStyles, /\.ui-gallery__grid\s*\{[^}]*align-items:\s*start/s)
})
