import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const root = process.cwd()

function read(relativePath) {
  return readFileSync(join(root, relativePath), 'utf8')
}

test('Sprint 7 UI Gallery route and mock data are present', () => {
  assert.equal(existsSync(join(root, 'src/renderer/src/features/gallery/UiGallery.tsx')), true)
  assert.equal(existsSync(join(root, 'src/renderer/src/features/gallery/uiGalleryMock.ts')), true)
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /#\/ui-gallery/)
  assert.match(app, /UiGallery/)
})

test('GoBoardV2 renders polished stone and candidate layers', () => {
  const board = read('src/renderer/src/features/board/GoBoardV2.tsx')
  assert.match(board, /ks-stone-highlight/)
  assert.match(board, /ks-board-bevel/)
  assert.match(board, /ks-candidate-soft-glow/)
  assert.match(board, /ks-candidate-winrate/)
  assert.match(board, /ks-candidate-visits/)
  assert.match(board, /ks-candidate-score/)
  assert.match(board, /PlayedMoveMark/)
  assert.match(board, /ks-played-move-layer/)
  const geometry = read('src/renderer/src/features/board/boardGeometry.ts')
  assert.match(geometry, /renderPlayedMove/)
  assert.match(geometry, /valueOf\(valueOf\(analysis, 'before'\), 'topMoves'\)/)
})

test('WinrateTimelineV2 exposes hover tooltip and score line rendering', () => {
  const timeline = read('src/renderer/src/features/board/WinrateTimelineV2.tsx')
  assert.match(timeline, /ks-timeline-tooltip/)
  assert.match(timeline, /ks-timeline-line--score/)
  assert.match(timeline, /extractScoreLead/)
  assert.match(timeline, /hoveredMove/)
  assert.match(timeline, /胜率 \/ 目差曲线/)
})

test('KataGo live analysis controls expose start pause and visit thresholds', () => {
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /BoardContextBar/)
  assert.match(app, /LIVE_ANALYSIS_VISIT_STEPS/)
  assert.match(app, /LIVE_ANALYSIS_TOTAL_VISIT_LIMIT/)
  assert.match(app, /LIVE_ANALYSIS_BEST_VISIT_LIMIT/)
  assert.match(app, /visitsPerSecond/)
  assert.match(app, /analyzePositionStream/)
  assert.match(app, /onAnalyzePositionProgress/)
  const katago = read('src/main/services/katago.ts')
  assert.match(katago, /reportDuringSearchEvery/)
  assert.match(katago, /isDuringSearch/)
  assert.match(app, /formatSearchSpeed/)
  assert.match(app, /userPausedLiveAnalysisRef/)
  assert.match(app, /startLiveAnalysis/)
  assert.match(app, /pauseLiveAnalysis/)
  assert.match(app, /开始分析/)
  assert.match(app, /暂停分析/)
  const styles = read('src/renderer/src/styles.css')
  assert.match(styles, /board-contextbar__metrics/)
  assert.match(styles, /analysis-control-strip/)
  assert.match(styles, /analysis-toggle-button/)
})

test('KataGo benchmark tuning is wired from main process to settings UI', () => {
  const types = read('src/main/lib/types.ts')
  assert.match(types, /KataGoBenchmarkResult/)
  assert.match(types, /katagoBenchmarkThreads/)
  const runtime = read('src/main/services/katagoRuntime.ts')
  assert.match(runtime, /numAnalysisThreads = \$\{analysisThreads\}/)
  assert.match(runtime, /numSearchThreadsPerAnalysisThread = \$\{searchThreadsPerAnalysisThread\}/)
  const benchmark = read('src/main/services/katagoBenchmark.ts')
  assert.match(benchmark, /benchmark/)
  assert.match(benchmark, /numSearchThreads/)
  assert.match(benchmark, /visitsPerSecond/)
  const preload = read('src/preload/index.ts')
  assert.match(preload, /benchmarkKataGo/)
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /KataGoBenchmarkPanel/)
  assert.match(app, /一键测速并优化/)
})

test('TeacherRunCardPro renders structured product modules', () => {
  const teacher = read('src/renderer/src/features/teacher/TeacherRunCardPro.tsx')
  assert.match(teacher, /一句话结论/)
  assert.match(teacher, /推荐思路/)
  assert.match(teacher, /可继续追问/)
  assert.match(teacher, /ks-teacher-pro-evidence/)
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /teacher-agent-editor/)
  assert.match(app, /TeacherInlineResponse/)
  assert.match(app, /codex-tool-trace/)
  assert.match(app, /agent-turn/)
  assert.match(app, /Agent thread/)
  assert.match(app, /搜索野狐棋谱/)
  const composer = read('src/renderer/src/features/teacher/TeacherComposerPro.tsx')
  assert.match(composer, /Ask KataSensei/)
  assert.match(composer, /ks-composer-pro__actions/)
  assert.match(composer, /ks-composer-pro__chrome/)
  const agent = read('src/main/services/teacherAgent.ts')
  assert.match(agent, /像人类围棋老师讲棋/)
  assert.doesNotMatch(agent, /请优先输出 JSON/)
})

test('Desktop app shell exposes native menu commands and workbench chrome', () => {
  const main = read('src/main/index.ts')
  assert.match(main, /Menu\.setApplicationMenu/)
  assert.match(main, /desktop:command/)
  assert.match(main, /CommandOrControl\+K/)
  const preload = read('src/preload/index.ts')
  assert.match(preload, /onDesktopCommand/)
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /DesktopTitleBar/)
  assert.match(app, /CommandPalette/)
  assert.match(app, /DesktopPreferencesModal/)
  assert.match(app, /DesktopStatusBar/)
  const styles = read('src/renderer/src/styles.css')
  assert.match(styles, /desktop-shell/)
  assert.match(styles, /desktop-command-palette/)
  assert.match(styles, /desktop-statusbar/)
  assert.match(styles, /desktop-command-palette__list strong[^}]+#f8f1e4/s)
  assert.match(styles, /desktop-command-palette__panel input::placeholder/)
})

test('StudentRailCard stays compact and visual QA capture exists', () => {
  const student = read('src/renderer/src/features/student/StudentRailCard.tsx')
  assert.match(student, /gameCount/)
  assert.match(student, /未绑定棋手/)
  assert.match(student, /onChangeBinding/)
  assert.doesNotMatch(student, /trainingFocus/)
  assert.doesNotMatch(student, /分析最近 10 局/)
  const app = read('src/renderer/src/App.tsx')
  assert.match(app, /loadBoundPlayer/)
  const main = read('src/main/index.ts')
  assert.match(main, /student:for-game/)
  const preload = read('src/preload/index.ts')
  assert.match(preload, /getStudentForGame/)
  assert.equal(existsSync(join(root, 'scripts/capture_ui_gallery.mjs')), true)
  assert.equal(existsSync(join(root, 'docs/VISUAL_QA_CAPTURE.md')), true)
})
